# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7eca7d99850fcb35eaa73c95f786434f9aec54708a5398dd9bcd1b1c25bd75fd948b9d0f10cd78962b79be4ff9b91f920f5916db95eb62023e3c441bf81c4cb0

test:
  secret_key_base: ebf1cc42d72798912c2cf5c263fe224feccb42428c51075a45a0c99f31acf77cc3a499479e2d40fc689bc763be1d5c69baffb7936da169527e71367067235626

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
